name: wordpress-pro-lyrid-2
description: App Description
ignoreFiles: .git
operator: true
modules:
  - name: container
    language: docker
    description: Module description
    container: 
    volumes:
    ports:
      - alias: "http"
        port: 80
    functions:
      - name: entry
        description: the entry point for the function